theme: jekyll-theme-cayman
title: FacebookPy | Facebook Like/Comment/Follow Automation Script
description: An automation script that uses your Facebook account to like and follow others with the aim of them liking and following back
